# Generated by Django 4.1.7 on 2023-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='static/images/places/'),
        ),
    ]
